[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "^4"
uuid = { version = "0.8", features = ["v4"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["postgres", "chrono"] }
diesel_derives = "1.4"
dotenv = "0.15"
log = "0.4.22"
env_logger = "0.11.5"
